# fastapi-service Service
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi-service  # 이걸 Deployment와 맞추기
  ports:
    - port: 1248
      targetPort: 1542