version: '3.8'

services:
  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    networks:
      - cloud-public
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - ./loki-data:/loki

  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    networks:
      - cloud-public
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana


volumes:
  grafana-storage:

networks:
  cloud-public:
    driver: bridge