version: '3.8'

services:
  reverse-proxy:
      image: traefik:v2.2
      command:
        - --providers.docker
        - --providers.docker.endpoint=tcp://socket-proxy:2375
        - --providers.docker.swarmMode 
        - --providers.docker.exposedbydefault=false
        - --entrypoints.web.address=:80
        - --providers.docker.network=cloud-public
        - --api
        - --api.dashboard=true
        - --api.insecure=true
        - --entrypoints.websecure.address=:443 # HTTPS 포트
        - --certificatesresolvers.mytlschallenge.acme.tlschallenge=true # TLS Challenge 사용
        - --certificatesresolvers.mytlschallenge.acme.email=jwsjws99@gmail.com #Let's Encrypt 인증만료 알림 이메일
        - --certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json
        - --certificatesresolvers.mytlschallenge.acme.httpchallenge.entryPoint=websecure

        # Logging
        - --accesslog
        - --log.level=debug

        #Prometheus Metric
        - --metrics.prometheus=true
        - --metrics.prometheus.buckets=0.1, 0.3, 1.2, 5.0
        - --metrics.prometheus.addEntryPointsLabels=true
        - --metrics.prometheus.addServicesLabels=true
        # - --entryPoints.metrics.address=:9090
        # - --metrics.prometheus.entryPoint=metrics

        

      deploy:
        mode: replicated 
        replicas: 1
        update_config:
          order: start-first 
          delay: 10s
          failure_action: rollback 
        rollback_config:
          order: stop-first
          parallelism: 0
        restart_policy:
          condition: on-failure
          delay: 30s
          max_attempts: 3 
        placement:
          constraints:
            - node.role == manager
        labels:
          # # Global redirection: HTTP to HTTPS
          - traefik.http.routers.http-redirects.entrypoints=web
          - traefik.http.routers.http-redirects.rule=hostregexp(`{host:(www\.)?.+}`)
          - traefik.http.routers.http-redirects.middlewares=traefik-ratelimit,redirect-to-non-www-https

          # # Global redirection: HTTPS www to HTTPS non-www
          - traefik.http.routers.www-redirects.entrypoints=websecure
          - traefik.http.routers.www-redirects.rule=hostregexp(`{host:(www\.).+}`)
          - traefik.http.routers.www-redirects.tls=true
          - traefik.http.routers.www-redirects.tls.options=default

          # # Middleware to redirect to bare https
          - traefik.http.middlewares.redirect-to-non-www-https.redirectregex.regex=^https?://(?:www\.)?(.+)
          - traefik.http.middlewares.redirect-to-non-www-https.redirectregex.replacement=https://$${1}
          - traefik.http.middlewares.redirect-to-non-www-https.redirectregex.permanent=true


      ports:
        - target: 80
          published: 80
          protocol: tcp
          mode: host
        - target: 443
          published: 443
          protocol: tcp
          mode: host
        - target: 8080
          published: 8080
          protocol: tcp
          mode: host
      volumes:
        # storage for the SSL certificates
        - /Users/oldentomato/Desktop/vscode/tomatoAgent/letsencrypt:/letsencrypt
        # bind mount the directory for your traefik configuration
        - /Users/oldentomato/Desktop/vscode/tomatoAgent/traefik_conf:/traefik_conf
        # - /var/run/docker.sock:/var/run/docker.sock
      networks:
        - cloud-public