version: '3.8'

services:

  spring-service:
    image: oldentomato/planner:0.6
    build:
      context: .
      dockerfile: ./spring/Dockerfile
    networks:
      - cloud-public
    ports:
      - "8099:8099"

  fastapi-service:
    image: oldentomato/travel-fastapi:0.1
    ports:
      - "1248:1542"
    env_file:
      - ./fastapiEnv/.env
    volumes:
      - chatdata-storage:/app/save_chat
    depends_on:
      - mysql
      - redis
    restart: unless-stopped
    networks:
      - cloud-public

# port 6379
  redis:
    image: redis:latest
    networks:
      - cloud-public
    deploy:
      resources:
        limits:
          memory: 400M
    tty: true

# port 3306
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ${MYSQL_VOLUME_PATH}:/var/lib/mysql
    networks:
      - cloud-public

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=mysql  # 연결할 기본 DB 호스트 (필요에 따라 수정)
    networks:
      - cloud-public

volumes:
  chatdata-storage:

networks:
  cloud-public:
    driver: bridge